language: objective-c
osx_image: xcode9
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone X"
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus"
    - DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"
    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4s"
script:
  - set -o pipefail
  - xcodebuild -project "Pancake.xcodeproj" -scheme "Pancake" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  - xcodebuild -project "Pancake.xcodeproj" -scheme "Pancake" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
